//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCAT_2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCAT_2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.7 jquery.com | jquery.org/license */
        ///(function(a,b){function cA(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cx(a){if(!cm[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){cn||(cn=c.createElement(&quot;iframe&quot;),cn.frameBorder=cn.width=cn.height=0),b.appendChild(cn);if(!co||!cn.createElement)co=(cn.contentWindow||cn.contentDocument).document,co.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body&gt;&quot;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_7_min {
            get {
                return ResourceManager.GetString("jquery_1_7_min", resourceCulture);
            }
        }
        
        internal static byte[] libblas {
            get {
                object obj = ResourceManager.GetObject("libblas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libblas1 {
            get {
                object obj = ResourceManager.GetObject("libblas1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libgcc_s_dw2_1 {
            get {
                object obj = ResourceManager.GetObject("libgcc_s_dw2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] libgfortran_3 {
            get {
                object obj = ResourceManager.GetObject("libgfortran_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] liblapack {
            get {
                object obj = ResourceManager.GetObject("liblapack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] liblapack1 {
            get {
                object obj = ResourceManager.GetObject("liblapack1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Define the overlay, derived from google.maps.OverlayView
        ///function Label(opt_options) {
        /// // Initialization
        /// this.setValues(opt_options);
        ///
        /// // Label specific
        /// var span = this.span_ = document.createElement(&apos;span&apos;);
        /// span.style.cssText = &apos;position: relative; left: -50%; top: -48px; &apos; +
        ///                      &apos;white-space: nowrap; border: none; &apos; +
        ///                      &apos;background-color: #FFFFE0; font-family:arial,sans-serif;&apos; +
        ///                      &apos;font-weight:bold; font-size:small; color:black&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mapLabel {
            get {
                return ResourceManager.GetString("mapLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon SCAT_Logo1 {
            get {
                object obj = ResourceManager.GetObject("SCAT_Logo1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] scat2 {
            get {
                object obj = ResourceManager.GetObject("scat2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] scat21 {
            get {
                object obj = ResourceManager.GetObject("scat21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;initial-scale=1.0, user-scalable=no&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///      html { height: 100% }
        ///      body { height: 100%; margin: 0; padding: 0 }
        ///      #map_canvas { height: 100% }
        ///     
        ///      .infoWindow
        ///      {
        ///      color: red;
        ///      background-color: #BBBBBB;
        ///      width: 70px;
        ///      height: 15px;
        ///      font-size: 10pt;
        ///      }
        ///
        ///      .left {
        ///      font-size: 20pt;
        ///      }
        ///
        ///      .separator {
        ///      clear: both;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SCATPlot {
            get {
                return ResourceManager.GetString("SCATPlot", resourceCulture);
            }
        }
        
        internal static byte[] voronoi {
            get {
                object obj = ResourceManager.GetObject("voronoi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] voronoi1 {
            get {
                object obj = ResourceManager.GetObject("voronoi1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
